server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0
        - id: test-route
          uri: https://httpbin.org/get
          predicates:
            - Path=/test
