name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: neomart_db
          POSTGRES_USER: neomart_user
          POSTGRES_PASSWORD: neomart_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test product-service
        working-directory: ./product-service
        run: ./gradlew clean build

      - name: Build and test api-gateway
        working-directory: ./api-gateway
        run: ./gradlew clean build

      - name: SonarQube Scan (product-service)
        working-directory: ./product-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=product_service_key \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${SONAR_TOKEN}

      - name: SonarQube Scan (api-gateway)
        working-directory: ./api-gateway
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=api_gateway_key \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${SONAR_TOKEN}